---
namespace: argocd

resources:
  - core/namespace.yaml
  - core/secrets-store.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.14.8/manifests/core-install.yaml

  # Configuration
  - config/argocd-clusters.yaml
  - config/argocd-ingress.yaml
  - config/argocd-projects.yaml
  - config/argocd-repos.yaml
  - config/argocd-secret.yaml

  # Resources
  - resources

  # Apps
  - apps

patches:
  - path: patches/argocd-server.yaml
  - path: patches/argocd-application-controller.yaml
  - path: patches/argocd-secrets-mounts.yaml
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-cm-params-cm.yaml
  - path: patches/argocd-rbac-cm.yaml
  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-secret
      $patch: delete
  - patch: |-
      apiVersion: v1
      kind: Deployment
      metadata:
        name: argocd-repo-server
      spec:
        template:
          spec:
            containers:
              - name: argocd-repo-server
                env:
                  - name: ARGOCD_EXEC_TIMEOUT
                    value: 240s
