---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - https://github.com/jorgepezuela/lab/tree/develop/kubernetes/core/

---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  destinations:
    - namespace: "*"
      server: "*"
  sourceRepos:
    - https://github.com/jorgepezuela/lab/tree/develop/kubernetes/apps
    - https://github.com/jorgepezuela/lab/tree/develop/kubernetes/microservices-template
